# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_receita', '0001_initial'),
        ('app_base', '0001_initial'),
        ('app_contrato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamemto_plano_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendence', models.CharField(choices=[('Atendimento clinico', 'Atendimento clinico'), ('Exame clinico', 'Exame clinico')], max_length=150)),
                ('date_atendence', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contrato.Contrato_nutricionista')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendamento para planos Nutri',
            },
        ),
        migrations.CreateModel(
            name='agendamemto_plano_odonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendence', models.CharField(choices=[('Atendimento clinico', 'Atendimento clinico'), ('Exame clinico', 'Exame clinico')], max_length=150)),
                ('date_atendence', models.DateField()),
                ('active', models.BooleanField()),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contrato.Contrato_odonto')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendamento para planos odonto',
            },
        ),
        migrations.CreateModel(
            name='agendamemto_plano_psico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendence', models.CharField(choices=[('Atendimento clinico', 'Atendimento clinico'), ('Exame clinico', 'Exame clinico')], max_length=150)),
                ('date_atendence', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contrato.Contrato_psicologo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendamento para planos Psico',
            },
        ),
        migrations.CreateModel(
            name='agendamento_simples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendence', models.CharField(choices=[('Atendimento clinico', 'Atendimento clinico'), ('Exame clinico', 'Exame clinico')], max_length=150)),
                ('date_atendence', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendamento simples',
            },
        ),
        migrations.CreateModel(
            name='relatorio_exame_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_atendence', models.DateField()),
                ('date_now', models.DateField(auto_now=True)),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Relatorio de Exame Nutri',
            },
        ),
        migrations.CreateModel(
            name='relatorio_exame_odonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_atendence', models.DateField()),
                ('date_now', models.DateField(auto_now=True)),
                ('note', models.TextField()),
                ('faces_tooths', models.ManyToManyField(to='app_receita.FacesDentes')),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('tooths', models.ManyToManyField(to='app_receita.Dentes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Relatorio de Exame Odonto',
            },
        ),
        migrations.CreateModel(
            name='relatorio_exame_psico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_atendence', models.DateField()),
                ('date_now', models.DateField(auto_now=True)),
                ('note', models.TextField()),
                ('name_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Relatorio de Exame Psico',
            },
        ),
    ]
