# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_exame_odonto_continuado',
            name='image_register',
            field=models.ImageField(blank=True, null=True, upload_to='documents/relatorio/exame/%Y/%m/%d'),
        ),
    ]
