# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atendimento', '0002_relatorio_exame_nutri_continuado_relatorio_exame_odonto_continuado_relatorio_exame_psico_continuado'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento_plano_filiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendence', models.CharField(choices=[('Atendimento clinico', 'Atendimento clinico'), ('Exame clinico', 'Exame clinico')], max_length=150)),
                ('date_atendence', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Agendamento de Afiliados de convenios com empresas',
            },
        ),
        migrations.AddField(
            model_name='relatorio_exame_odonto_continuado',
            name='image_register',
            field=models.ImageField(blank=True, null=True, upload_to='/imagem_contrato_odonto/'),
        ),
    ]
