# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contrato', '0004_auto_20170727_2325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_atendimento', '0003_auto_20170727_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento_plano_filiado',
            name='name_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contrato.Contrato_Filiado_A_Empresa'),
        ),
        migrations.AddField(
            model_name='agendamento_plano_filiado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
