# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_Paga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_to', models.CharField(max_length=150)),
                ('value_count', models.FloatField()),
                ('date_to_payment', models.DateField(unique_for_date=True)),
                ('frequencia', models.CharField(choices=[('Periodica', 'Periodica'), ('Corriqueira', 'Corriqueira')], max_length=15)),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], max_length=15)),
            ],
        ),
    ]
