# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_receita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentes',
            options={'verbose_name_plural': 'Dente'},
        ),
        migrations.AlterModelOptions(
            name='facesdentes',
            options={'verbose_name_plural': 'Faces do Dente'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoplanonutri',
            options={'verbose_name_plural': 'Orcamento Plano Nutricionista'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoplanoodontologico',
            options={'verbose_name_plural': 'Orcamento Plano Odonto'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoplanopsico',
            options={'verbose_name_plural': 'Orcamento Plano Psicologia'},
        ),
        migrations.AlterModelOptions(
            name='tipo_recebimento',
            options={'verbose_name_plural': 'Tipo de Recebimento'},
        ),
    ]
