# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_profissionais_salary'),
        ('app_receita', '0002_auto_20170630_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.FloatField()),
                ('odonto', models.BooleanField()),
                ('nutri', models.BooleanField()),
                ('pscico', models.BooleanField()),
                ('professional', models.ManyToManyField(blank=True, to='app_base.Profissionais')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentoplanonutri',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamentoplanoodontologico',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamentoplanopsico',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recebimentoavulso',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recebimentoavulso',
            name='value_tratment',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoplanonutri',
            name='services',
            field=models.ManyToManyField(blank=True, to='app_receita.Servicos'),
        ),
        migrations.AddField(
            model_name='orcamentoplanoodontologico',
            name='services',
            field=models.ManyToManyField(to='app_receita.Servicos'),
        ),
        migrations.AddField(
            model_name='orcamentoplanopsico',
            name='services',
            field=models.ManyToManyField(blank=True, to='app_receita.Servicos'),
        ),
        migrations.AddField(
            model_name='recebimentoavulso',
            name='services',
            field=models.ManyToManyField(blank=True, to='app_receita.Servicos'),
        ),
    ]
