# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('date_register', models.DateField(help_text='A data sugerida para pagamento mensal!')),
                ('profession', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('rg', models.CharField(max_length=25, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birth_day', models.DateField()),
                ('Note', models.TextField(blank=True)),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cotatos_Clientes_indicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('cliente', models.BooleanField()),
                ('indicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Indicados',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_entry', models.DateField()),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('function', models.CharField(choices=[('Gerente', 'Gerente'), ('Zelador(a)', 'Zelador(a)'), ('Atendente', 'Atendente'), ('Vigia', 'Vigia'), ('Seguranca', 'Seguranca')], max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('rg', models.CharField(max_length=25, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('birth_day', models.DateField()),
                ('note', models.TextField()),
                ('salary', models.FloatField()),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('professional_as', models.CharField(choices=[('Dentista', 'Dentista'), ('Nutricionista', 'Nutricionista'), ('Psicologo', 'Psicologo')], max_length=150)),
                ('salary', models.FloatField()),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('register', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('birth_day', models.DateField()),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
