# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('date_register', models.DateField(help_text='A data sugerida para pagamento mensal!')),
                ('profession', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('rg', models.CharField(db_index=True, max_length=25)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('birth_day', models.DateField()),
                ('Note', models.TextField(blank=True)),
                ('active', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical cliente',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFuncionario',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('date_entry', models.DateField()),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('function', models.CharField(choices=[('Gerente', 'Gerente'), ('Zelador(a)', 'Zelador(a)'), ('Atendente', 'Atendente'), ('Vigia', 'Vigia'), ('Seguranca', 'Seguranca')], max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('rg', models.CharField(db_index=True, max_length=25)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('cep', models.CharField(max_length=9)),
                ('birth_day', models.DateField()),
                ('note', models.TextField()),
                ('salary', models.FloatField()),
                ('active', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical funcionario',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProfissionais',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('professional_as', models.CharField(choices=[('Dentista', 'Dentista'), ('Nutricionista', 'Nutricionista'), ('Psicologo', 'Psicologo')], max_length=150)),
                ('salary', models.FloatField()),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('register', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('birth_day', models.DateField()),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical profissionais',
            },
        ),
    ]
