# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_receita', '0001_initial'),
        ('app_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_nutricionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_contract', models.DateField(blank=True, help_text='Data para finalizar o tratamento')),
                ('type_plane', models.CharField(choices=[('Plano', 'Plano'), ('Avulso', 'Avulso')], max_length=150)),
                ('plane_value', models.FloatField()),
                ('date_payment_per_month', models.CharField(help_text='O dia do vencimento para o mes.', max_length=2)),
                ('input_value', models.FloatField(blank=True, help_text='Valor dado de entrada, pode deixar em branco caso fique sem a entrada!')),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_receita.OrcamentoPlanoNutri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_odonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_contract', models.DateField(blank=True, help_text='Data para finalizar o tratamento')),
                ('type_plane', models.CharField(choices=[('Plano', 'Plano'), ('Avulso', 'Avulso')], max_length=150)),
                ('plane_value', models.FloatField()),
                ('date_payment_per_month', models.CharField(help_text='O dia do vencimento para o mes.', max_length=2)),
                ('input_value', models.FloatField(blank=True, help_text='Valor dado de entrada, pode deixar em branco caso fique sem a entrada!')),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_receita.OrcamentoPlanoOdontologico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_contract', models.DateField(blank=True, help_text='Data para finalizar o tratamento')),
                ('type_plane', models.CharField(choices=[('Plano', 'Plano'), ('Avulso', 'Avulso')], max_length=150)),
                ('plane_value', models.FloatField()),
                ('date_payment_per_month', models.CharField(help_text='O dia do vencimento para o mes.', max_length=2)),
                ('input_value', models.FloatField(blank=True, help_text='Valor dado de entrada, pode deixar em branco caso fique sem a entrada!')),
                ('note', models.TextField()),
                ('active', models.BooleanField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais')),
                ('propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_receita.OrcamentoPlanoPsico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
