# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato_nutricionista',
            name='date_today',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato_odonto',
            name='date_today',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato_psicologo',
            name='date_today',
            field=models.DateField(auto_now=True),
        ),
    ]
