# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato_odonto',
            name='cortesia',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
