# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_base', '0002_profissionais_salary'),
        ('app_contrato', '0003_auto_20170721_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_Filiado_A_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('registration', models.CharField(blank=True, max_length=150, unique=True)),
                ('type_plane', models.CharField(blank=True, choices=[('Plano', 'Plano'), ('Avulso', 'Avulso')], max_length=150)),
                ('date_today', models.DateField(auto_now=True, unique_for_date=True)),
                ('date_payment_per_month', models.CharField(blank=True, help_text='O dia do vencimento para o mes.', max_length=2)),
                ('active', models.BooleanField()),
                ('image_register', models.ImageField(blank=True, null=True, upload_to='/imagem_contrato_odonto/')),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contrato de filiacao a empresa',
            },
        ),
        migrations.AddField(
            model_name='contrato_empresa',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato_empresa',
            name='contract_date',
            field=models.DateField(auto_now=True, unique_for_date=True),
        ),
        migrations.AddField(
            model_name='contrato_empresa',
            name='social_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato_filiado_a_empresa',
            name='associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contrato.Contrato_Empresa'),
        ),
        migrations.AddField(
            model_name='contrato_filiado_a_empresa',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_base.Profissionais'),
        ),
        migrations.AddField(
            model_name='contrato_filiado_a_empresa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
